@url = http://localhost/ecommerce/public/api
@contentTypeJson = application/json
@contentTypeUrlEncoded= = application/x-www-form-urlencoded


### (GET) all products ######################################################################
GET {{url}}/products

### (GET) one products ######################################################################
GET {{url}}/products/30